# Generated by Django 4.2.7 on 2023-11-09 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0002_alter_task_options_alter_task_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("task_done", "-datetime_field")},
        ),
    ]
